### ISSUE TITLE
Fedora 32, build failure

### ISSUE THREAD

**Issue by SteveEbey73742** [JoaoBaptMG/INF443-Project#1]
steps I took.
Clone git
mkdir build
cmake -S . -B build

found required library files, and failed with the following error.

CMake Error at CMakeLists.txt:37 (add_executable):
  Target "INF443Project" links to target "assimp::assimp" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

**Comment by JoaoBaptMG** [comment]
This is because you must install `libassimp-dev` in your operating system. Unfortunately, I saw (at least in `apt-get`) that Assimp is a bit buggy, so it might be better to [clone it from source](https://github.com/assimp/assimp) and compiling it.

**Comment by SteveEbey73742** [comment]
assimp and all devel files for it, from the Fedora repositories are installed. edited cmake, changed assimp::assimp to just assimp and cmake ran.  Now for the fun, the errors on comile are shown here.+

/home/steve/Projects/INF443-Project/src/model/ModelMaterial.cpp: In constructor ‘model::ModelMaterial::ModelMaterial(std::filesystem::__cxx11::path, model::Model&, const aiScene*, const aiMaterial*)’:
/home/steve/Projects/INF443-Project/src/model/ModelMaterial.cpp:19:35: error: ‘const struct aiScene’ has no member named ‘GetEmbeddedTexture’
   19 |         if (auto texture = scene->GetEmbeddedTexture(path.C_Str()))
      |                                   ^~~~~~~~~~~~~~~~~~
/home/steve/Projects/INF443-Project/src/model/ModelMaterial.cpp:32:35: error: ‘const struct aiScene’ has no member named ‘GetEmbeddedTexture’
   32 |         if (auto texture = scene->GetEmbeddedTexture(path.C_Str()))
      |                                   ^~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/INF443Project.dir/build.make:291: CMakeFiles/INF443Project.dir/src/model/ModelMaterial.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/INF443Project.dir/all] Error 2
make: *** [Makefile:104: all] Error 2

**Comment by JoaoBaptMG** [comment]
Okay, the Fedora packages use an old Assimp version. Taken from [here](https://pkgs.org/download/assimp(x86-64)), the assimp version is 3.3.1 and the Assimp I am using, the most recent one, is 5.0.1. So, I guess you'd better by uninstalling all packages and cloning from Assimp's repository and compiling/installing it yourself.

**Comment by SteveEbey73742** [comment]
built successfully, ran and the window opens, and shows the image, mouse moves camera around. Are there any command line options that need to be tested.  While running, the terminal is filled with 
NG_ARB (2), and GL_ARRAY_BUFFER_ARB, usage hint is GL_STREAM_DRAW) will use VIDEO memory as the source for buffer object operations.
[notification] other (API): Buffer detailed info: Buffer object 215 (bound to GL_ELEMENT_ARRAY_BUFFER_ARB, usage hint is GL_STREAM_DRAW) will use VIDEO memory as the source for buffer object operations.
[notification] other (API): Buffer detailed info: Buffer object 214 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (1), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (2), and GL_ARRAY_BUFFER_ARB, usage hint is GL_STREAM_DRAW) will use VIDEO memory as the source for buffer object operations.
[notification] other (API): Buffer detailed info: Buffer object 215 (bound to GL_ELEMENT_ARRAY_BUFFER_ARB, usage hint is GL_STREAM_DRAW) will use VIDEO memory as the source for buffer object operations.
[notification] other (API): Buffer detailed info: Buffer object 214 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (1), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (2), and GL_ARRAY_BUFFER_ARB, usage hint is GL_STREAM_DRAW) will use VIDEO memory as the source for buffer object operations.
[notification] other (API): Buffer detailed info: Buffer object 215 (bound to GL_ELEMENT_ARRAY_BUFFER_ARB, usage hint is GL_STREAM_DRAW) will use VIDEO memory as the source for buffer object operations.
[notification] other (API): Buffer detailed info: Buffer object 214 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (1), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (2), and GL_ARRAY_BUFFER_ARB, usage hint is GL_STREAM_DRAW) will use VIDEO memory as the source for buffer object operations.
 but the program runs fine.  hope this is the outcome you were expecting

**Comment by JoaoBaptMG** [comment]
No, that’s all I need to hear! Thank you for your help.
Besides, the messages you’re getting are diagnostic messages that aren’t turned on on the Release build, so you might want to set the CMake build to Release. That was what I was expecting. Thank you a lot!
